Traceback (most recent call last):
  File "/Volumes/GoogleDrive/Mon Drive/Documents/Cours/Google IT Automation with Python Professional Certificate/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
